const Actions = {
	ADD_SCROLL_LISTENER: 'ADD_SCROLL_LISTENER',
	SCROLL: {
		INIT: 'SCROLL_INIT'
	},
	POSTS: {
		REQUEST: 'POSTS_REQUEST',
		SUCCESS: 'POSTS_SUCCESS',
		ERROR: 'POSTS_ERROR'
	}
};

export default Actions;