const Actions = {
	SCROLL: {
		INIT: 'SCROLL_INIT',
		ADD_LISTENER: 'SCROLL_ADD_LISTENER',
		REMOVE_LISTENER: 'SCROLL_REMOVE_LISTENER'
	},
	POSTS: {
		REQUEST: 'POSTS_REQUEST',
		SUCCESS: 'POSTS_SUCCESS',
		ERROR: 'POSTS_ERROR'
	},
	AUTH: {
		LOGIN: 'LOGIN',
		LOGOUT: 'LOGOUT'
	}
};

export default Actions;